version: "3.8"

services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    image: naica922/app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_DEFER-DATASOURCE-INITIALIZATION: "true"
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
      LOGGING_LEVEL_ROOT: info
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      JWT_ISSUER: uk223
      JWT_EXPIRATION_MILLIS: 100000000
    depends_on:
      - db
  frontend:
    image: naica922/app:latest
    ports:
      - "80:80"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
    depends_on:
      - backend

volumes:
  postgres-data: