version: "3.8"

services:
  db:
    image: postgres:16
    container_name: mydb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    image: naica922/app:latest
    container_name: mybackend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_DEFER-DATASOURCE-INITIALIZATION: "true"
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
    depends_on:
      - db

volumes:
  postgres-data: