name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world with secret
        run: echo "Hello World! - the secret is ${{ secrets.MY_SECRET }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Script
        run: |
          chmod +x run.sh
          ./run.sh

      - name: Executing remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          script: echo "Hello World"
