name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello World! - the secret is ${{ secrets.MY_SECRET }}"

      - name: Run shell script
        run: |
          chmod +x script.sh
          ./script.sh
